## DevOps Information ###
devops_user_story:
  add:
    fields:
      - name: customer_name
        label: Customer
        type: select
        options: []
        options_source: customer_data
        optional: False
      - name: user_story_name
        label: User Story Title
        type: input
        optional: False
      - name: state
        label: State
        type: select
        options:
          - New
          - Active
          - Resolved
          - Closed
          - Removed
        default: New
        optional: False
      - name: source
        label: Source
        type: select
        options:
          - Teams
          - Email
          - Call
          - In person
          - Other
        default: Other
        optional: False
      - name: contact_person
        label: Contact Person
        type: input
        optional: True
      - name: assigned_to
        label: Assigned To
        type: input
        optional: True
      - name: tags
        label: Tags
        type: chip_group
        options: []
        options_source: devops_tags
        optional: True
      - name: parent_name
        label: Parent (Epic/Feature)
        type: select
        options: []
        options_source: parent_names
        optional: False
        parent: customer_name
      - name: priority
        label: Priority
        type: select
        options:
          - 1
          - 2
          - 3
          - 4
        default: 2
        optional: False
      - name: item_date
        label: Recieved Date
        type: date
        options: []
        options_source: today
        optional: true
      - name: problem_description
        label: Problem Description
        type: text
        optional: True
      - name: more_info
        label: More Information
        type: text
        optional: True
      - name: solution
        label: Solution
        type: text
        optional: True
      - name: validation
        label: Validation
        type: text
        optional: True
      - name: use_markdown
        label: Use Markdown
        type: switch
        optional: False
        default: True
    columns:
      - [
          customer_name,
          parent_name,
          user_story_name,
          contact_person,
          assigned_to,
        ]
      - [tags, state, source, priority, item_date]
      - [problem_description, more_info, solution, validation, use_markdown]
    action:
      function: add_user_story
      main_action: User Story
      main_param: user_story_name
      secondary_action: added
      button_name: "Add"
  update:
    fields:
      - name: customer_name
        label: Customer
        type: select
        options: []
        options_source: customer_data
        optional: False
      - name: work_item
        label: Work Item (Epic/Feature/User Story)
        type: select
        options: []
        options_source: work_items
        optional: False
        parent: customer_name
      - name: description_editor
        label: Description Editor
        type: codemirror
        type_language: markdown
        optional: False
      - name: description_preview
        label: Preview
        type: html
        optional: False
        parent: description_editor
        parent_update: True
        render_function: render_and_sanitize
    rows:
      - [customer_name, work_item]
      - [description_editor, description_preview]
    action:
      function: update_work_item_description
      main_action: Work Item
      main_param: work_item
      secondary_action: updated
      button_name: Save
