## DevOps Information ###
devops_work_item:
  add:
    fields:
      - name: customer_name
        label: Customer
        type: select
        options: []
        options_source: customer_data
        optional: False
      - name: work_item_type
        label: Work Item Type
        type: select
        options:
          - Epic
          - Feature
          - User Story
        default: User Story
        optional: False
      - name: work_item_title
        label: Title
        type: input
        optional: False
      - name: state
        label: State
        type: select
        options:
          - New
          - Active
          - Resolved
          - Closed
          - Removed
        default: New
        optional: False
      - name: source
        label: Source
        type: select
        with_input: true
        options:
          - Teams
          - Email
          - Call
          - In person
          - Other
        optional: True
        conditional: true
        visible_when:
          work_item_type: [User Story]
      - name: contact_person
        label: Contact Person
        type: select
        with_input: true
        options: []
        options_source: contact_persons
        optional: True
        parent: customer_name
        conditional: true
        visible_when:
          work_item_type: [User Story]
      - name: assigned_to
        label: Assigned To
        type: select
        with_input: true
        options: []
        options_source: assignees
        default_source: default_assignee
        optional: True
        parent: customer_name
      - name: tags
        label: Tags
        type: chip_group
        options: []
        options_source: devops_tags
        optional: True
      - name: parent_name
        label: Parent
        type: select
        options: []
        options_source: parent_names
        optional: True
        parent: customer_name
        conditional: true
        visible_when:
          work_item_type: [Feature, User Story]
      - name: priority
        label: Priority
        type: select
        options:
          - 1
          - 2
          - 3
          - 4
        default: 2
        optional: False
      - name: use_markdown
        label: Use Markdown
        type: switch
        optional: False
        default: True
      - name: description_editor
        label: Description Editor
        type: codemirror
        type_language: markdown
        optional: False
        parent_fields: [source, contact_person]
        templates:
          Epic: |
            **Created Date:** {today}

            ## Strategic Goal


            ## Business Value


            ## Success Criteria


            ## Timeline

          Feature: |
            **Created Date:** {today}

            ## Feature Description


            ## Business Value


            ## Acceptance Criteria


            ## Dependencies

          User Story: |
            **Received Date:** {today}
            **Source:** 
            **Contact:** 

            ## Problem


            ## More Information


            ## Solution


            ## Validation

      - name: description_preview
        label: Preview
        type: html
        optional: True
        parent: description_editor
        parent_update: True
        render_function: render_and_sanitize
    rows:
      - [customer_name, work_item_type, work_item_title]
      - [parent_name, assigned_to]
      - [contact_person, source]
      - [state, priority]
      - [tags]
      - [description_editor, description_preview]
    action:
      function: add_work_item
      main_action: Work Item
      main_param: work_item_title
      secondary_action: added
      button_name: "Add"
  update:
    fields:
      - name: customer_name
        label: Customer
        type: select
        options: []
        options_source: customer_data
        optional: False
      - name: work_item
        label: Work Item
        type: select
        options: []
        options_source: work_items
        optional: False
        parent: customer_name
      - name: state
        label: State
        type: select
        options:
          - New
          - Active
          - Resolved
          - Closed
          - Removed
        optional: True
      - name: assigned_to
        label: Assigned To
        type: select
        with_input: true
        options: []
        options_source: assignees
        optional: True
        parent: customer_name
      - name: priority
        label: Priority
        type: select
        options:
          - 1
          - 2
          - 3
          - 4
        optional: True
      - name: description_editor
        label: Description Editor
        type: codemirror
        type_language: markdown
        optional: False
      - name: description_preview
        label: Preview
        type: html
        optional: True
        parent: description_editor
        parent_update: True
        render_function: render_and_sanitize
    rows:
      - [customer_name, work_item]
      - [state, assigned_to, priority]
      - [description_editor, description_preview]
    action:
      function: update_work_item
      main_action: Work Item
      main_param: work_item
      secondary_action: updated
      button_name: Save
